logging:
  config: classpath:logback-spring-dev.xml
spring:
  r2dbc:
    url: "r2dbc:mysql://127.0.0.1:3306/coroutine-project?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false"
    username: admin
    password: admin
    pool:
      enabled: true
      max-size: 64
      initial-size: 10
      validation-query: select 1
  redis:
    host: 127.0.0.1
    port: 6379

sms:
  server:
    provider:
      ali-yun:
        sign-name: xxx
        access-key-id: xxx
        access-secret: xxx

ideal:
  snowflake:
    factory-type: redis
    data-center-id: 0

